"use client"

import * as React from "react"
import Link from "next/link"
import { Sparkles } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { supabase } from "../../src/lib/supabase"

type ResearchRun = {
  id: string
  agent_id: string
  agent_name: string
  run_type: string
  summary: string | null
  recommendation: unknown
  status: string
  created_at: string
}

export default function ResearchPage() {
  const [runs, setRuns] = React.useState<ResearchRun[]>([])
  const [loading, setLoading] = React.useState(true)
  const [error, setError] = React.useState("")

  React.useEffect(() => {
    let cancelled = false

    async function loadRuns() {
      const { data: sessionData } = await supabase.auth.getSession()
      const token = sessionData.session?.access_token
      const res = await fetch("/api/research/runs", {
        cache: "no-store",
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
      const payload = await res.json()

      if (cancelled) return

      if (!payload.success) {
        setError(payload.error || "Failed to load research runs.")
        setRuns([])
      } else {
        setRuns(payload.runs || [])
      }
      setLoading(false)
    }

    loadRuns()

    return () => {
      cancelled = true
    }
  }, [])

  const dailyRuns = runs.filter((run) => run.run_type === "daily")
  const weeklyRuns = runs.filter((run) => run.run_type === "weekly")
  const escalationRuns = runs.filter((run) => run.run_type === "escalation")

  return (
    <div className="mx-auto w-full max-w-7xl px-4 pb-16 pt-8 sm:px-6 lg:px-10">
      <div className="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
          <p className="font-mono text-[11px] tracking-widest text-muted-foreground uppercase">
            Intelligence / Research
          </p>
          <h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">
            Agent Research Center
          </h1>
          <p className="mt-2 max-w-3xl text-sm text-muted-foreground">
            Research output is generated by Daily, Weekly, and Escalation agent runs. No static market briefs are shown here.
          </p>
        </div>
        <Button asChild className="gap-2 bg-primary/90 shadow-lg shadow-primary/20 hover:bg-primary">
          <Link href="/agents">
            <Sparkles className="size-4" />
            Run Agent Research
          </Link>
        </Button>
      </div>

      {error && (
        <Card className="mb-4 border-destructive/40 bg-destructive/10">
          <CardContent className="py-3 text-sm text-destructive">{error}</CardContent>
        </Card>
      )}

      <section className="mb-6 grid gap-4 md:grid-cols-3">
        <MetricCard label="Daily Runs" value={loading ? "..." : String(dailyRuns.length)} />
        <MetricCard label="Weekly Runs" value={loading ? "..." : String(weeklyRuns.length)} />
        <MetricCard label="Escalations" value={loading ? "..." : String(escalationRuns.length)} />
      </section>

      <Card className="border-border/60 bg-card/55 backdrop-blur-md">
        <CardHeader>
          <CardTitle>Recent Research Runs</CardTitle>
          <CardDescription>
            Latest non-rebalance research generated by visible agents.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <p className="text-sm text-muted-foreground">Loading research runs...</p>
          ) : runs.length === 0 ? (
            <div className="rounded-lg border border-dashed border-border/70 p-6 text-sm text-muted-foreground">
              No research runs yet. Open an agent and run Daily, Weekly, or Escalation.
            </div>
          ) : (
            <div className="space-y-3">
              {runs.map((run) => (
                <Link
                  key={run.id}
                  href={`/agents/${run.agent_id}`}
                  className="block rounded-lg border border-border/60 bg-muted/20 p-4 transition hover:border-primary/40"
                >
                  <div className="mb-2 flex flex-wrap items-center justify-between gap-3">
                    <div>
                      <p className="font-medium">{run.agent_name}</p>
                      <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                        {formatToken(run.run_type)} / {new Date(run.created_at).toLocaleString()}
                      </p>
                    </div>
                    <span className="rounded-md border border-border/70 px-2 py-1 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
                      {run.status}
                    </span>
                  </div>
                  <p className="line-clamp-3 text-sm leading-relaxed text-muted-foreground">
                    {run.summary || summarizeRecommendation(run.recommendation)}
                  </p>
                </Link>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

function MetricCard({ label, value }: { label: string; value: string }) {
  return (
    <Card className="border-border/60 bg-card/55 backdrop-blur-md">
      <CardHeader>
        <CardDescription>{label}</CardDescription>
        <CardTitle className="text-3xl tabular-nums">{value}</CardTitle>
      </CardHeader>
    </Card>
  )
}

function summarizeRecommendation(value: unknown) {
  if (!value || typeof value !== "object") return "No summary returned."
  const record = value as Record<string, unknown>

  return (
    readString(record.executive_summary) ||
    readString(record.market_summary) ||
    readString(record.summary) ||
    "Research run completed."
  )
}

function readString(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : ""
}

function formatToken(value: string) {
  return value.replaceAll("_", " ")
}
