import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

const briefs = [
  {
    title: "US Macro Brief",
    summary: "Core inflation cools while labor remains tight; risk assets supported short term.",
    stamp: "Updated 14m ago",
  },
  {
    title: "Semiconductor Weekly",
    summary: "AI accelerator demand remains robust; supply constraints likely ease in Q3.",
    stamp: "Updated 42m ago",
  },
  {
    title: "Energy and Commodities",
    summary: "Oil range-bound; gold bid sustained on real-rate uncertainty and geopolitical risk.",
    stamp: "Updated 1h ago",
  },
]

const reports = [
  { week: "Week 18", title: "Cross-Asset Correlation Drift", status: "Published" },
  { week: "Week 17", title: "Earnings Revision Breadth", status: "Published" },
  { week: "Week 16", title: "Liquidity Stress Test", status: "Archived" },
]

export default function ResearchPage() {
  return (
    <div className="mx-auto w-full max-w-7xl px-4 pb-16 pt-8 sm:px-6 lg:px-10">
      <div className="mb-6">
        <p className="font-mono text-[11px] tracking-widest text-muted-foreground uppercase">
          Intelligence / Research
        </p>
        <h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">AI Research Center</h1>
      </div>

      <section className="mb-6 grid gap-4 lg:grid-cols-3">
        {briefs.map((brief) => (
          <Card key={brief.title} className="border-border/60 bg-card/55 backdrop-blur-md">
            <CardHeader>
              <CardTitle className="text-base">{brief.title}</CardTitle>
              <CardDescription>{brief.summary}</CardDescription>
            </CardHeader>
            <CardContent className="font-mono text-[11px] tracking-wide text-muted-foreground">
              {brief.stamp}
            </CardContent>
          </Card>
        ))}
      </section>

      <Card className="border-border/60 bg-card/55 backdrop-blur-md">
        <CardHeader>
          <CardTitle>Weekly Reports</CardTitle>
          <CardDescription>Research packets generated by simulation agents.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          {reports.map((report) => (
            <div
              key={report.week}
              className="flex items-center justify-between rounded-lg border border-border/60 bg-muted/20 px-3 py-2"
            >
              <div>
                <p className="font-medium">{report.title}</p>
                <p className="font-mono text-[10px] tracking-wide text-muted-foreground uppercase">{report.week}</p>
              </div>
              <span className="rounded-md border border-border/70 bg-muted/40 px-2 py-1 font-mono text-[10px] tracking-wider text-muted-foreground uppercase">
                {report.status}
              </span>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  )
}
